### PR TITLE
Adding zip target to mac build in order to generate latest-mac.yml file

### PR DESCRIPTION
**Pull request by thehogfather**
This adds a zip target for the wallet build output. This is required for electron autoupdate to work (see Note 2 [here](https://www.electron.build/auto-update)).

### Context
There has been some intent to leverage the auto-update feature of electron for the desktop wallet to make the update process more user friendly e.g., [here](https://trello.com/c/R6y26I12/396-auto-update-round-2). The electron auto update plugin requires certain artefacts (`latest.yml, latest-mac.yml`) to be generated along side the installers found on the github release pages. These are currently not generated. Explicitly adding a `zip` target to the mac build configuration should cause the files to be generated.

Please let me know when merged and a new build is run.

### CODE REVIEW

**Comment by goldylucks** [comment]
@thehogfather the build is failing, but I don't think it's related to your change. I have restarted the build, standing by ...

**Comment by goldylucks** [comment]
ok, so after doing 2 rebuilds thru Travis CI interface, I see error is persisting:

```
$ npm ci
npm WARN prepare removing existing node_modules/ before installation
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR!
npm ERR!
npm ERR! Invalid: lock file's @zen/zen-node@0.9.16 does not satisfy @zen/zen-node@0.9.17
```

Try fixing this with `$ npm install` and commit the changes?

**Comment by thehogfather** [comment]
> ok, so after doing 2 rebuilds thru Travis CI interface, I see error is persisting:
> 
> ```
> $ npm ci
> npm WARN prepare removing existing node_modules/ before installation
> npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
> npm ERR!
> npm ERR!
> npm ERR! Invalid: lock file's @zen/zen-node@0.9.16 does not satisfy @zen/zen-node@0.9.17
> ```
> Try fixing this with `$ npm install` and commit the changes?

@goldylucks Thanks! done.
I initially chose to not commit the lock file - as I was running npm 5.x locally - and the diffs on the lock file were pretty outrageious. I think the rest of the team runs npm 6.x (which seems to generate some reasonable diffs)

**Comment by goldylucks** [comment]
ok, I'm rebasing this and merging

**Comment by goldylucks** [comment]
Closed in favor of #123 , in order to rebase and produce a `package-lock.json` file withnpm 6

**Pull request closed without merging**
